
#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <Arduino.h>

#define MAX_VELOCITY 1
#define START_DELAY_TIME 3000

#define US_EDGE_THRESHOLD 200
#define US_OBSTACLE_THRESHOLD 5

#define DEBUG 1

#define IR_THRESHOLD 500

/********************
 * Pins
*********************/
#define US_FRONT_LEFT_TRIGGER_PIN 46
#define US_FRONT_LEFT_ECHO_PIN 47

#define US_FRONT_RIGHT_TRIGGER_PIN 44
#define US_FRONT_RIGHT_ECHO_PIN 45

#define US_FRONT_MIDDLE_TRIGGER_PIN 42
#define US_FRONT_MIDDLE_ECHO_PIN 43

#define US_DOWN_LEFT_TRIGGER_PIN 50
#define US_DOWN_LEFT_ECHO_PIN 51

#define US_DOWN_RIGHT_TRIGGER_PIN 52
#define US_DOWN_RIGHT_ECHO_PIN 53

#define US_REAR_LEFT_TRIGGER_PIN 48
#define US_REAR_LEFT_ECHO_PIN 49

#define IR_FRONT_LEFT_PIN 30
#define IR_FRONT_RIGHT_PIN 31
#define IR_REAR_LEFT_PIN 32
#define IR_REAR_RIGHT_PIN 33

#define START_BUTTON_PIN 29

#define LINE_FOLLOWER_PIN0 A0
#define LINE_FOLLOWER_PIN1 A1
#define LINE_FOLLOWER_PIN2 A2
#define LINE_FOLLOWER_PIN3 A3
#define LINE_FOLLOWER_PIN4 A4

#define LED_RED_PIN 113
#define LED_GREEN_PIN 12
#define LED_BLUE_PIN 11

#define STEPPER_MOTOR_PIN1 7
#define STEPPER_MOTOR_PIN2 8
#define STEPPER_MOTOR_PIN3 9
#define STEPPER_MOTOR_PIN4 10

#define MOTOR_PIN1 1
#define MOTOR_PIN2 2
#define MOTOR_ENA1 5

#define MOTOR_PIN3 3
#define MOTOR_PIN4 4
#define MOTOR_ENA2 7

#define DEGREES_CIRCLES 360

#endif